# basic application info
id: test
name: Test application
description: |
  This is a very long string with a test application description.
  Multiline and stuff
version: v1

# command to be executed as child service
command: sh test.sh

# response endpoint
responseEndpoint: http://localhost:3000

# input schema
inputSchema:
  type: object
  properties:
    subobj:
      type: object
      properties:
        test:
          type: string
      required:
        - test
    text:
      type: string
  required:
    - text

# output schema
outputSchema:
  type: object
  properties:
    text:
      type: string
    sentiments:
      type: array
      minItems: 1

# config schema
configSchema:
  type: object
  properties:
    sentimentConfig:
      type: object
      properties:
        one:
          type: string
      required:
        - one
  required:
    - sentimentConfig
